---
- name: Ensure dirmngr is installed (gnupg dependency).
  apt:
    name: dirmngr
    state: present
    update_cache: true

- name: Install Ansible.
  apt:
    name: ansible
    state: "{{ ansible_package_state }}"
