---
# See: https://github.com/kubernetes/kubernetes/issues/71305
- name: Use iptables-legacy instead of nftables.
  alternatives:
    name: '{{ item.name }}'
    path: '{{ item.path }}'
  with_items:
    - { name: iptables, path: /usr/sbin/iptables-legacy }
    - { name: ip6tables, path: /usr/sbin/ip6tables-legacy }

- name: Update cache
  apt:
    update_cache: yes

# See: https://www.jeffgeerling.com/k8s-cni-virtualbox
- name: Retrieve current Flannel manifest from GitHub.
  get_url:
    url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    dest: ~/kube-flannel.yml
  when: inventory_hostname == 'bastion'

- name: Patch Flannel manifest with VirtualBox interface.
  patch:
    src: files/diff.patch
    dest: ~/kube-flannel.yml
  when: inventory_hostname == 'bastion'

- name: Set the correct path for the patched Flannel manifest.
  set_fact:
    kubernetes_flannel_manifest_file: ~/kube-flannel.yml
  when: inventory_hostname == 'bastion'

- name: Install Java on slave.
  apt: 
    name: openjdk-8-jdk
    state: present
  when: inventory_hostname == 'slave1'

- name: Copy jenkins public key to his slave
  template:
    src: MasterSlave.pub
    dest: /tmp/MasterSlave.pub
  when: inventory_hostname == 'slave1'

- name: line insert
  lineinfile:
    path: /home/ubuntu/.ssh/authorized_keys
    line: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSBPD+IG+aSGMUx8EKivw6zsmtIDwHXHIUiCiGCvluXspPNHBgzhitvcI/wMcMtbvfisKmhdWpUFHSYGZl6eayJQ3vO1IiIGvi4qNN2+qcjmRWu4K5GntZslPCQ/yGqh240cQSzbmK5LWnITyzZZO5K9/3gJ2koOUg8WrR2DsYlxYyUIIqw/9MK5sbTF1hpZ+6edxQbRUHLoiYJyVPptwpAK2C1hpn3o1/fb5creAkPvrrtf7rhce2BibLx9SqE+ieOWKNnFJJPoRiKewxnUEDV8YOOVsdr8KoztuyDR5fLkyPFIOgfNxxMgCd5xJK20yhsthUgrl4KFgyXGl9clD3 user@Computer'
    insertbefore: EOF
  when: inventory_hostname == 'slave1'

- name: Copy jenkins public key to his slave
  template:
    src: MasterSlave.pub
    dest: /tmp/MasterSlave.pub
  when: inventory_hostname == 'bastion'

- name: line insert
  lineinfile:
    path: /home/ubuntu/.ssh/authorized_keys
    line: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSBPD+IG+aSGMUx8EKivw6zsmtIDwHXHIUiCiGCvluXspPNHBgzhitvcI/wMcMtbvfisKmhdWpUFHSYGZl6eayJQ3vO1IiIGvi4qNN2+qcjmRWu4K5GntZslPCQ/yGqh240cQSzbmK5LWnITyzZZO5K9/3gJ2koOUg8WrR2DsYlxYyUIIqw/9MK5sbTF1hpZ+6edxQbRUHLoiYJyVPptwpAK2C1hpn3o1/fb5creAkPvrrtf7rhce2BibLx9SqE+ieOWKNnFJJPoRiKewxnUEDV8YOOVsdr8KoztuyDR5fLkyPFIOgfNxxMgCd5xJK20yhsthUgrl4KFgyXGl9clD3 user@Computer'
    insertbefore: EOF
  when: inventory_hostname == 'bastion'
  